import { Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactQueryProvider } from "./Reactquery/ReactqueryProvider";
import Nav from "./components/Nav";




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-inter" >
        <ReactQueryProvider>
        
          {children}

        </ReactQueryProvider>
      </body>
    </html>
  );
}
